name = "RecursiveGPs"
uuid = "d96faaa6-41d2-4991-8e2f-b0cd4a4b0e9a"
version = "0.1.0"
authors = ["Martin Cornejo <martin.cornejo@tum.de>", "Juan Victor Sandalinas <go69lif@mytum.de>"]

[deps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
Optimization = "7f7a1694-90dd-40f0-9382-eb1efda571ba"
OptimizationOptimJL = "36348300-93cb-4f02-beb5-3c3902f8871e"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
CairoMakie = "0.15.8"
Optimization = "5.3.0"
OptimizationOptimJL = "0.4.8"
StatsBase = "0.34.9"
