name = "RecursiveGPs"
uuid = "d96faaa6-41d2-4991-8e2f-b0cd4a4b0e9a"
version = "0.1.0"
authors = ["Martin Cornejo <martin.cornejo@tum.de>", "Juan Victor Sandalinas <go69lif@mytum.de>"]

[deps]
AbstractGPs = "99985d1d-32ba-4be9-9821-2ec096f28918"
ComponentArrays = "b0b7db55-cfe3-40fc-9ded-d10e2dbeff66"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LowLevelParticleFilters = "d9d29d28-c116-5dba-9239-57a5fe23875b"
PreallocationTools = "d236fae5-4411-538c-8e31-a6e3d9e00b46"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
AbstractGPs = "0.5.24"
ComponentArrays = "0.15.31"
ForwardDiff = "1.3.1"
LinearAlgebra = "1.12.0"
LowLevelParticleFilters = "3.28.0"
PreallocationTools = "1.0.0"
StaticArrays = "1.9.16"
Statistics = "1.11.1"



[extras]
LineSearches = "d3d80556-e9d4-5f37-9878-2ab0fcc64255"
Optimization = "7f7a1694-90dd-40f0-9382-eb1efda571ba"
OptimizationOptimJL = "36348300-93cb-4f02-beb5-3c3902f8871e"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["LineSearches", "Optimization", "OptimizationOptimJL", "Random", "Test"]