[deps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
LineSearches = "d3d80556-e9d4-5f37-9878-2ab0fcc64255"
Optimization = "7f7a1694-90dd-40f0-9382-eb1efda571ba"
OptimizationOptimJL = "36348300-93cb-4f02-beb5-3c3902f8871e"
RecursiveGPs = "d96faaa6-41d2-4991-8e2f-b0cd4a4b0e9a"

[sources]
RecursiveGPs = {path = ".."}
